name: CI Security
on:
  push:
    branches: [ desarrollo ]
jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: SAST con Semgrep
        run: semgrep --config auto src/app.js
      - name: Escaneo de dependencias
        run: npm audit
