name: CI Security
on:
  push:
    branches: [ desarrollo ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
      - name: SAST con Semgrep
        uses: semgrep/semgrep-action@v1
        with:
          config: auto
      - name: Escaneo de dependencias
        run: npm audit || true
